[package]
name = "opys-java"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
description = "opys JDK provisioning plugin — Temurin, Zulu and GraalVM CE resolvers."

[dependencies]
opys-core = { path = "../opys-core", version = "0.2.0" }
opys-dev = { path = "../opys-dev", version = "0.2.0" }
indexmap = { version = "2", features = ["serde"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
percent-encoding = "2"

[dev-dependencies]
opys-dev = { path = "../opys-dev", version = "0.2.0" }
